#!/bin/sh

set -e -x

apk update

apk add --no-cache python3=${PYTHON3_VERSION}
apk add --no-cache py-pip make g++ python3-dev

python3 -m pip install --no-cache-dir --upgrade pip
python3 -m pip install --no-cache-dir pylint==${PYLINT_VERSION}
python3 -m pip install --no-cache-dir mypy==${MYPY_VERSION}

python3 -m pip uninstall -y pip
find /usr/lib/ -type d -name __pycache__ -exec rm -r {} \+
apk del py-pip make g++ python3-dev
